name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }} #Definido em Setttinh > Security > Secrets and variables > Actions
        password: ${{ secrets.DOCKERHUB_PASS }} #Definido em Setttinh > Security > Secrets and variables > Actions
    
    - name: Construir e enviar a imagem para o Docker Registry
      run: echo "executar o docker build"

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./imersao-devops-cloud-02\kube-news\src
        file: ./imersao-devops-cloud-02\kube-news\src\Dockerfile
        push: true
        tags: |
          esfonseca99/kube-news:${{ github.run_number }}
          esfonseca99/kube-news:latest
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
      
    - name: Configuração das credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key:  ${{ secrets.AWS_ACCESS_KEY_PASS }}
        aws-region: us-east-1
      
    - name: Configurar o KubeConfig
      run: echo "Configurar o KubeConfig"
    - name: Aplicar o Deploy
      run: echo "Executar o kubectl apply"
